# .github/workflows/release.yaml

on:
  push:

name: Build Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.4'
  
    - run: go build ./cmd/oj

    - run: ls