# .github/workflows/release.yaml

on:
  push:

name: Build Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.4'
  
    - run: go build -o oj_linux_amd64 ./cmd/oj
    - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o oj_windows_amd64 ./cmd/oj
    - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o oj_darwin_amd64 ./cmd/oj

    - run: ls