# .github/workflows/release.yaml

on:
  push:

name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "1.22.6"

      - run: go build -o oj_linux_amd64 .
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o oj_windows_amd64.exe .
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o oj_darwin_amd64 .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            oj_linux_amd64
            oj_windows_amd64.exe
            oj_darwin_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
